### ISSUE TITLE
how to install plugin on  Canvas

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-canvas#2]
kaltura is a popular plugin for Canvas

**Comment by zengxc-1996** [comment]
How to install the plugin can be found here.
[Canvas Integration]https://github.com/instructure/canvas-lms/wiki/Canvas-Integration

**Comment by qiaofeng1227** [comment]
step:
1. login in your canvas website
2. access  by your http://your domain or public ip/plugins
![image](https://user-images.githubusercontent.com/43192516/121460490-9636dd00-c9df-11eb-9d86-3f4983756d01.png)
3.select you want to install plugin，and click install
![image](https://user-images.githubusercontent.com/43192516/121459915-ae5a2c80-c9de-11eb-83b3-8808bb6b9002.png)
![image](https://user-images.githubusercontent.com/43192516/121459936-bdd97580-c9de-11eb-91b3-5bfe4e1fb6e0.png)
4. the changes about canvas
![image](https://user-images.githubusercontent.com/43192516/121459399-bfef0480-c9dd-11eb-9e6a-6a3a843fe5a9.png)
![image](https://user-images.githubusercontent.com/43192516/121460121-009b4d80-c9df-11eb-9680-6ad2aad373eb.png)

**Comment by qiaofeng1227** [comment]
Done

**Comment by qiaofeng1227** [comment]
http://support.websoft9.com/docs/canvas/zh/else-faq.html#canvas-%E6%94%AF%E6%8C%81%E4%B8%AD%E6%96%87%E5%90%97
